# Travis-CI Build for OpenRA
# see travis-ci.org for details

language: csharp
mono: 4.6.1

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

cache:
  directories:
  - thirdparty/download

addons:
  apt:
    packages:
    - lua5.1
    - nsis
    - nsis-common
    - dpkg
    - markdown
    - zlib1g-dev
    - libbz2-dev
    - cmake
    - genisoimage
    - fakeroot
    - zsync

# Environment variables
env:

# Fetch dependencies
# Run the build script
# Check source code with StyleCop
# call OpenRA to check for YAML errors
# Run the NUnit tests
script:
 - travis_retry make all-dependencies
 - make all SDK="-sdk:4.5"
 - make check
 - make check-scripts
# - make test
 - make nunit

# Automatically update the trait documentation and Lua API
after_success:
# - test $TRAVIS_PULL_REQUEST == "false" && cd packaging && ./update-wiki.sh $TRAVIS_BRANCH; cd ..

# Only watch the development branch and tagged release.
branches:
 only:
  - master

# Notify developers when build passed/failed.
notifications:
  webhooks: http://attsup.swr-productions.com/travis-ci/travis-ci.php


#before_deploy:
# - export PATH=$PATH:$HOME/usr/bin
# - DOTVERSION=`echo ${TRAVIS_TAG} | sed "s/-/\\./g"`
# - cd packaging
# - mkdir build
# - ./package-all.sh ${TRAVIS_TAG} ${PWD}/build/
#deploy:
#  provider: releases
#  api_key:
#    secure:
#  file_glob: true
#  file: build/*
#  skip_cleanup: true
#  on:
#    all_branches: true
#    tags: true
#    repo: AttacqueSuperior/Engine
